version: '3.9'

services:
  convert_app:
    image: convert_app
    container_name: convert_app
    stdin_open: true
    tty: true
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
